[env:nrf52840_dk]
platform      = nordicnrf52
board         = nrf52840_dk
framework     = none
build_flags   =
    -Iinclude
    -I../../../include
    -mcpu=cortex-m4
    -mthumb
    -mfpu=fpv4-sp-d16
    -mfloat-abi=hard
    -O2
    -Wall
extra_scripts = pre:../../../scripts/link_ktos.py
build_src_filter = +<src/> +<../../../bsp/nrf52840/>
monitor_speed = 115200
