var searchData=
[
  ['c_20code_20style_0',['c code style',['../md_CONTRIBUTING.html#autotoc_md72',1,'C Code Style'],['../md_CODE__OF__CONDUCT.html#autotoc_md84',1,'C Code Style']]],
  ['cd_20pipeline_1',['CI / CD Pipeline',['../index.html#autotoc_md53',1,'']]],
  ['checklist_2',['Porting checklist',['../ktos__hal_8h.html#autotoc_md6',1,'']]],
  ['ci_20cd_20pipeline_3',['CI / CD Pipeline',['../index.html#autotoc_md53',1,'']]],
  ['clock_5finit_5f48mhz_4',['clock_init_48MHz',['../startup_8c.html#a0b551273446a40b6642560095f9498a2',1,'startup.c']]],
  ['code_5',['Platform-Specific Code',['../md_CODE__OF__CONDUCT.html#autotoc_md87',1,'']]],
  ['code_20documentation_6',['Code Documentation',['../md_CODE__OF__CONDUCT.html#autotoc_md97',1,'']]],
  ['code_20of_20conduct_7',['code of conduct',['../md_CONTRIBUTING.html#autotoc_md63',1,'Code of Conduct'],['../md_CODE__OF__CONDUCT.html#autotoc_md78',1,'Code of Conduct'],['../md_CODE__OF__CONDUCT.html',1,'Code of Conduct']]],
  ['code_20organization_8',['Code Organization',['../md_CODE__OF__CONDUCT.html#autotoc_md85',1,'']]],
  ['code_20style_9',['code style',['../md_CODE__OF__CONDUCT.html#autotoc_md84',1,'C Code Style'],['../md_CONTRIBUTING.html#autotoc_md72',1,'C Code Style']]],
  ['code_5fof_5fconduct_2emd_10',['CODE_OF_CONDUCT.md',['../CODE__OF__CONDUCT_8md.html',1,'']]],
  ['coding_20standards_11',['coding standards',['../md_CODE__OF__CONDUCT.html#autotoc_md83',1,'Coding Standards'],['../md_CONTRIBUTING.html#autotoc_md71',1,'Coding Standards']]],
  ['commercial_20license_12',['Commercial License',['../index.html#autotoc_md59',1,'']]],
  ['commit_20guidelines_13',['commit guidelines',['../md_CONTRIBUTING.html#autotoc_md73',1,'Commit Guidelines'],['../md_CODE__OF__CONDUCT.html#autotoc_md88',1,'Commit Guidelines']]],
  ['commit_20message_20format_14',['Commit Message Format',['../md_CODE__OF__CONDUCT.html#autotoc_md89',1,'']]],
  ['conduct_15',['conduct',['../md_CODE__OF__CONDUCT.html',1,'Code of Conduct'],['../md_CONTRIBUTING.html#autotoc_md63',1,'Code of Conduct'],['../md_CODE__OF__CONDUCT.html#autotoc_md78',1,'Code of Conduct']]],
  ['constants_16',['KTOS Types — structs, enums, and constants',['../group__ktos__types.html',1,'']]],
  ['constraints_17',['constraints',['../pic18f_2ktos__bsp_8c.html#autotoc_md30',1,'Architecture constraints'],['../stm32f030_2ktos__bsp_8c.html#autotoc_md35',1,'Cortex-M0 assembly constraints'],['../stm32l031_2ktos__bsp_8c.html#autotoc_md40',1,'Cortex-M0+ assembly constraints']]],
  ['contents_18',['contents',['../md_CONTRIBUTING.html#autotoc_md62',1,'Table of Contents'],['../md_CODE__OF__CONDUCT.html#autotoc_md77',1,'Table of Contents']]],
  ['context_20frame_20layout_2064_20bytes_2016_20byte_20aligned_20grows_20downward_19',['Context frame layout (64 bytes, 16-byte aligned, grows downward)',['../esp8266_2ktos__bsp_8c.html#autotoc_md25',1,'']]],
  ['contributing_20',['Contributing',['../index.html#autotoc_md54',1,'']]],
  ['contributing_20to_20ktos_21',['Contributing to KTOS',['../md_CONTRIBUTING.html',1,'']]],
  ['contributing_2emd_22',['CONTRIBUTING.md',['../CONTRIBUTING_8md.html',1,'']]],
  ['cooperative_20task_20switcher_23',['KTOS — Tiny Cooperative Task Switcher',['../index.html',1,'']]],
  ['core_20—_20scheduler_20and_20task_20management_24',['KTOS Core — scheduler and task management',['../group__ktos__core.html',1,'']]],
  ['cortex_20m_20example_25',['cortex m example',['../group__ktos__hal.html#autotoc_md10',1,'Cortex-M example'],['../group__ktos__hal.html#autotoc_md8',1,'Cortex-M example']]],
  ['cortex_20m_20stm32f103_20stm32f030_26',['KTOS BSP — ARM Cortex-M (STM32F103, STM32F030)',['../group__ktos__bsp__arm.html',1,'']]],
  ['cortex_20m_20systick_20example_2072_20mhz_27',['Cortex-M SysTick example (72 MHz)',['../group__ktos__hal.html#autotoc_md13',1,'']]],
  ['cortex_20m0_28',['KTOS BSP — STM32L031 (Cortex-M0+)',['../group__ktos__bsp__stm32l031.html',1,'']]],
  ['cortex_20m0_20assembly_20constraints_29',['cortex m0 assembly constraints',['../stm32f030_2ktos__bsp_8c.html#autotoc_md35',1,'Cortex-M0 assembly constraints'],['../stm32l031_2ktos__bsp_8c.html#autotoc_md40',1,'Cortex-M0+ assembly constraints']]],
  ['cortex_20m3_20skeleton_30',['Cortex-M3 skeleton',['../group__ktos__hal.html#autotoc_md11',1,'']]],
  ['ctc_20example_2016_20mhz_20prescaler_2064_20ocr1a_20249_31',['AVR Timer1 CTC example (16 MHz, prescaler 64, OCR1A = 249)',['../group__ktos__hal.html#autotoc_md12',1,'']]]
];
