var searchData=
[
  ['c_20code_20style_0',['c code style',['../md_CODE__OF__CONDUCT.html#autotoc_md83',1,'C Code Style'],['../md_CONTRIBUTING.html#autotoc_md71',1,'C Code Style']]],
  ['cd_20pipeline_1',['CI / CD Pipeline',['../index.html#autotoc_md52',1,'']]],
  ['checklist_2',['Porting checklist',['../ktos__hal_8h.html#autotoc_md6',1,'']]],
  ['ci_20cd_20pipeline_3',['CI / CD Pipeline',['../index.html#autotoc_md52',1,'']]],
  ['code_4',['Platform-Specific Code',['../md_CODE__OF__CONDUCT.html#autotoc_md86',1,'']]],
  ['code_20documentation_5',['Code Documentation',['../md_CODE__OF__CONDUCT.html#autotoc_md96',1,'']]],
  ['code_20of_20conduct_6',['code of conduct',['../md_CODE__OF__CONDUCT.html#autotoc_md77',1,'Code of Conduct'],['../md_CONTRIBUTING.html#autotoc_md62',1,'Code of Conduct'],['../md_CODE__OF__CONDUCT.html',1,'Code of Conduct']]],
  ['code_20organization_7',['Code Organization',['../md_CODE__OF__CONDUCT.html#autotoc_md84',1,'']]],
  ['code_20style_8',['code style',['../md_CODE__OF__CONDUCT.html#autotoc_md83',1,'C Code Style'],['../md_CONTRIBUTING.html#autotoc_md71',1,'C Code Style']]],
  ['code_5fof_5fconduct_2emd_9',['CODE_OF_CONDUCT.md',['../CODE__OF__CONDUCT_8md.html',1,'']]],
  ['coding_20standards_10',['coding standards',['../md_CODE__OF__CONDUCT.html#autotoc_md82',1,'Coding Standards'],['../md_CONTRIBUTING.html#autotoc_md70',1,'Coding Standards']]],
  ['commercial_20license_11',['Commercial License',['../index.html#autotoc_md58',1,'']]],
  ['commit_20guidelines_12',['commit guidelines',['../md_CODE__OF__CONDUCT.html#autotoc_md87',1,'Commit Guidelines'],['../md_CONTRIBUTING.html#autotoc_md72',1,'Commit Guidelines']]],
  ['commit_20message_20format_13',['Commit Message Format',['../md_CODE__OF__CONDUCT.html#autotoc_md88',1,'']]],
  ['conduct_14',['conduct',['../md_CODE__OF__CONDUCT.html',1,'Code of Conduct'],['../md_CODE__OF__CONDUCT.html#autotoc_md77',1,'Code of Conduct'],['../md_CONTRIBUTING.html#autotoc_md62',1,'Code of Conduct']]],
  ['constants_15',['KTOS Types — structs, enums, and constants',['../group__ktos__types.html',1,'']]],
  ['constraints_16',['constraints',['../pic18f_2ktos__bsp_8c.html#autotoc_md30',1,'Architecture constraints'],['../stm32f030_2ktos__bsp_8c.html#autotoc_md34',1,'Cortex-M0 assembly constraints'],['../stm32l031_2ktos__bsp_8c.html#autotoc_md39',1,'Cortex-M0+ assembly constraints']]],
  ['contents_17',['contents',['../md_CONTRIBUTING.html#autotoc_md61',1,'Table of Contents'],['../md_CODE__OF__CONDUCT.html#autotoc_md76',1,'Table of Contents']]],
  ['context_20frame_20layout_2064_20bytes_2016_20byte_20aligned_20grows_20downward_18',['Context frame layout (64 bytes, 16-byte aligned, grows downward)',['../esp8266_2ktos__bsp_8c.html#autotoc_md25',1,'']]],
  ['contributing_19',['Contributing',['../index.html#autotoc_md53',1,'']]],
  ['contributing_20to_20ktos_20',['Contributing to KTOS',['../md_CONTRIBUTING.html',1,'']]],
  ['contributing_2emd_21',['CONTRIBUTING.md',['../CONTRIBUTING_8md.html',1,'']]],
  ['cooperative_20task_20switcher_22',['KTOS — Tiny Cooperative Task Switcher',['../index.html',1,'']]],
  ['core_20—_20scheduler_20and_20task_20management_23',['KTOS Core — scheduler and task management',['../group__ktos__core.html',1,'']]],
  ['cortex_20m_20example_24',['cortex m example',['../group__ktos__hal.html#autotoc_md10',1,'Cortex-M example'],['../group__ktos__hal.html#autotoc_md8',1,'Cortex-M example']]],
  ['cortex_20m_20stm32f103_20stm32f030_25',['KTOS BSP — ARM Cortex-M (STM32F103, STM32F030)',['../group__ktos__bsp__arm.html',1,'']]],
  ['cortex_20m_20systick_20example_2072_20mhz_26',['Cortex-M SysTick example (72 MHz)',['../group__ktos__hal.html#autotoc_md13',1,'']]],
  ['cortex_20m0_27',['KTOS BSP — STM32L031 (Cortex-M0+)',['../group__ktos__bsp__stm32l031.html',1,'']]],
  ['cortex_20m0_20assembly_20constraints_28',['cortex m0 assembly constraints',['../stm32f030_2ktos__bsp_8c.html#autotoc_md34',1,'Cortex-M0 assembly constraints'],['../stm32l031_2ktos__bsp_8c.html#autotoc_md39',1,'Cortex-M0+ assembly constraints']]],
  ['cortex_20m3_20skeleton_29',['Cortex-M3 skeleton',['../group__ktos__hal.html#autotoc_md11',1,'']]],
  ['ctc_20example_2016_20mhz_20prescaler_2064_20ocr1a_20249_30',['AVR Timer1 CTC example (16 MHz, prescaler 64, OCR1A = 249)',['../group__ktos__hal.html#autotoc_md12',1,'']]]
];
