#!/usr/bin/env python3
"""
make_trust_anchors.py — Convert PEM CA certificates to a BearSSL C trust anchor header.

Usage:
    python3 make_trust_anchors.py ca.pem [ca2.pem ...] > trust_anchors.h

Requires:
    pip install cryptography

For httpbin.org (Let's Encrypt):
    curl -o isrg_root_x1.pem https://letsencrypt.org/certs/isrgrootx1.pem
    python3 make_trust_anchors.py isrg_root_x1.pem > trust_anchors.h

For a custom server with a self-signed CA:
    python3 make_trust_anchors.py my_ca.pem > trust_anchors.h
"""

import sys

try:
    from cryptography import x509
    from cryptography.hazmat.primitives.asymmetric import rsa, ec
    from cryptography.hazmat.primitives.serialization import Encoding, PublicFormat
    from cryptography.hazmat.backends import default_backend
except ImportError:
    print("ERROR: 'cryptography' package not found.", file=sys.stderr)
    print("       Install with: pip install cryptography", file=sys.stderr)
    sys.exit(1)


def to_c_hex(data: bytes, name: str) -> str:
    cols = 12
    lines = []
    for i in range(0, len(data), cols):
        chunk = data[i:i + cols]
        lines.append('    ' + ', '.join(f'0x{b:02x}' for b in chunk))
    body = ',\n'.join(lines)
    return f'static const unsigned char {name}[] = {{\n{body}\n}};\n'


def process_cert(pem_path: str, idx: int):
    with open(pem_path, 'rb') as f:
        cert = x509.load_pem_x509_certificate(f.read(), default_backend())

    dn_der = cert.subject.public_bytes(default_backend())
    pub    = cert.public_key()

    output = [to_c_hex(dn_der, f'TA{idx}_DN')]

    if isinstance(pub, rsa.RSAPublicKey):
        nums    = pub.public_numbers()
        n_bytes = nums.n.to_bytes((nums.n.bit_length() + 7) // 8, 'big')
        e_bytes = nums.e.to_bytes((nums.e.bit_length() + 7) // 8, 'big')
        output.append(to_c_hex(n_bytes, f'TA{idx}_RSA_N'))
        output.append(to_c_hex(e_bytes, f'TA{idx}_RSA_E'))
        entry = (
            f'    {{\n'
            f'        {{ (unsigned char *)TA{idx}_DN, sizeof TA{idx}_DN }},\n'
            f'        BR_X509_TA_CA,\n'
            f'        {{\n'
            f'            BR_KEYTYPE_RSA,\n'
            f'            {{ .rsa = {{\n'
            f'                (unsigned char *)TA{idx}_RSA_N, sizeof TA{idx}_RSA_N,\n'
            f'                (unsigned char *)TA{idx}_RSA_E, sizeof TA{idx}_RSA_E,\n'
            f'            }} }}\n'
            f'        }}\n'
            f'    }}'
        )
    elif isinstance(pub, ec.EllipticCurvePublicKey):
        q_bytes = pub.public_bytes(Encoding.X962, PublicFormat.UncompressedPoint)
        curve_map = {
            'secp256r1': 'BR_EC_secp256r1',
            'secp384r1': 'BR_EC_secp384r1',
            'secp521r1': 'BR_EC_secp521r1',
        }
        curve_id = curve_map.get(pub.curve.name, 'BR_EC_secp256r1')
        output.append(to_c_hex(q_bytes, f'TA{idx}_EC_Q'))
        entry = (
            f'    {{\n'
            f'        {{ (unsigned char *)TA{idx}_DN, sizeof TA{idx}_DN }},\n'
            f'        BR_X509_TA_CA,\n'
            f'        {{\n'
            f'            BR_KEYTYPE_EC,\n'
            f'            {{ .ec = {{\n'
            f'                {curve_id},\n'
            f'                (unsigned char *)TA{idx}_EC_Q, sizeof TA{idx}_EC_Q,\n'
            f'            }} }}\n'
            f'        }}\n'
            f'    }}'
        )
    else:
        raise ValueError(f'Unsupported key type in {pem_path}: {type(pub).__name__}')

    subject = cert.subject.rfc4514_string()
    return f'/* {subject} */\n' + '\n'.join(output), entry


def main():
    if len(sys.argv) < 2:
        print(__doc__)
        sys.exit(1)

    pem_files = sys.argv[1:]
    entries, data_blocks = [], []

    for i, path in enumerate(pem_files):
        data, entry = process_cert(path, i)
        data_blocks.append(data)
        entries.append(entry)

    print('/* Auto-generated by make_trust_anchors.py — do not edit manually.')
    print(' * Regenerate: python3 make_trust_anchors.py <ca.pem> > trust_anchors.h */')
    print('#ifndef TRUST_ANCHORS_H')
    print('#define TRUST_ANCHORS_H')
    print()
    print('#include "lib/bearssl_inc/bearssl.h"')
    print()
    for block in data_blocks:
        print(block)
    print('static const br_x509_trust_anchor TAs[] = {')
    print(',\n'.join(entries))
    print('};')
    print()
    print('#define TAs_NUM  ((int)(sizeof TAs / sizeof TAs[0]))')
    print()
    print('#endif /* TRUST_ANCHORS_H */')


if __name__ == '__main__':
    main()
