[env:bluepill_f103c8]
platform      = ststm32
board         = bluepill_f103c8
framework     = none
build_flags   =
    -mcpu=cortex-m3
    -mthumb
    -O2
    -Wall
    -DSTM32F103C8
    -Isrc
upload_protocol = stlink
monitor_speed   = 115200
