[env:blackpill_f411ce]
platform      = ststm32
board         = blackpill_f411ce
framework     = none
build_flags   =
    -DSTM32F411xE
    -I../../../include
    -I../../../bsp/stm32f411ce
build_src_filter = +<src/>
monitor_speed = 115200
