; KTOS — STM32F103 Blue Pill ADC example (bare-metal)

[env:bluepill_f103c8]
platform             = ststm32
board                = bluepill_f103c8
upload_protocol      = stlink
monitor_speed        = 115200
board_build.ldscript = ../../../bsp/stm32f103/stm32f103.ld
build_src_filter =
    +<*>
    +<../../../../core/ktos.c>
    +<../../../../bsp/stm32f103/ktos_bsp.c>
    +<../../../../bsp/stm32f103/startup.c>
build_flags =
    -mcpu=cortex-m3 -mthumb -DF_CPU=72000000UL
    -Wall -Wextra -Os -ffunction-sections -fdata-sections
    -Wl,--gc-sections --specs=nosys.specs
    -I../../../core -I../../../bsp/stm32f103
