[env:disco_f407vg]
platform      = ststm32
board         = disco_f407vg
framework     = cmsis
build_flags   =
    -DSTM32F407xx
    -mcpu=cortex-m4
    -mthumb
    -mfpu=fpv4-sp-d16
    -mfloat-abi=hard
    -O2
    -Wall
    -Iinclude
    -I../../../include
build_src_filter = +<src/>
monitor_speed = 115200
